# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d09c788924dbb930719ed5515f1dca67c5ee339f4a926d3de8fd4614bcd0b19b1960119063bacbe92c540712fbbcf9dafc268606d6334c9e30f274d119a19d3

test:
  secret_key_base: 8feef885c92397c05f74abc0a5a718fdf73deb446581eba8daac333916bbcd7d61ea68288e207a5d67159f3b76d1a7e8be51d05dd5826883498256428e5121da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
